# aktus-embedding-service/values.yaml
aktusEmbedding:
  image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/aktus-ai/aktus-ai-platform-aws-marketplace-ecr:embedding-1.0.1
  imagePullPolicy: Always
  serviceAccount: aktus-ai-platform-sa
  port: 8080
  auth:
    username: "guest"
    password: "guest"
  uvicorn:
    host: "0.0.0.0"
    port: "8080"
    logLevel: "info"
    timeoutKeepalive: "3600"
  mdiService:
    endpoint: "http://aktus-multimodal-data-ingestion:5315"
  dbManager:
    host: "http://aktus-database"
  paths:
    extractedData: "/extracted_data"
    docUpload: "/document_upload"
    docProcessing: "/doc_processing"
    
  efs:
    fileSystemId: "fs-0d4f6da8071634ae0"
    
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
      ephemeral-storage: "5Gi"
    limits:
      cpu: "2000m"
      memory: "8Gi"
      
serviceAccount:
  name: "aktus-ai-platform-sa"