# charts/rabbitmq/values.yaml
rabbitmq:
  image: rabbitmq:3-management-alpine
  username: guest
  password: guest
  managementPort: 15672
  amqpPort: 5672
  service:
    type: ClusterIP
  definitions:
    enabled: true
    configMap: rabbitmq-definitions
  persistence:
    enabled: true
    storageClassName: gp2
    accessMode: ReadWriteOnce
    size: 50Gi
  efs:
    fileSystemId: "fs-placeholder"