apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.aktusMdi.efs.fileSystemId }}
    {{- if .Values.aktusMdi.efs.basePath }}
    volumeAttributes:
      path: {{ .Values.aktusMdi.efs.basePath | quote }}
    {{- end }} 