apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: {{ .Release.Name }}-{{ .Chart.Name }}-efs-pv
  resources:
    requests:
      storage: 5Gi 