apiVersion: v1
kind: Service
metadata:
  name: aktus-knowledge-assistant
  labels:
    app: aktus-knowledge-assistant-service
spec:
  type: {{ .Values.aktusKnowledgeAssistant.service.type }}
  ports:
    - port: {{ .Values.aktusKnowledgeAssistant.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aktus-knowledge-assistant-service