{{- if .Values.rabbitmq.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-rabbitmq-gp2-pv
spec:
  capacity:
    storage: {{ .Values.rabbitmq.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.rabbitmq.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.rabbitmq.persistence.storageClassName }}
  hostPath:
    path: /tmp/rabbitmq-data
    type: DirectoryOrCreate
{{- end }} 