{{- if .Values.rabbitmq.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-efs-pvc
spec:
  accessModes:
    - {{ .Values.rabbitmq.persistence.accessMode }}
  storageClassName: {{ .Values.rabbitmq.persistence.storageClassName }}
  volumeName: {{ .Release.Name }}-{{ .Chart.Name }}-efs-pv
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size }}
{{- end }} 