aktusKnowledgeAssistant:
  image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/aktus-ai/aktus-ai-platform-aws-marketplace-ecr:kda-1.0.0
  imagePullPolicy: Always
  port: 80
  service:
    type: ClusterIP
    port: 8080
  
  viteSocketUrl: "ws://aktus-research:8080/chat/copilot"
  viteApiBaseUrl: "http://aktus-db-manager:80"
  viteWaitlistFormId: "c989a45ed2991b0cb7455a37ced244f0"

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m" 
      memory: "1Gi"

serviceAccount:
  name: "aktus-ai-platform-sa"