{{- if .Values.qdrant.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
spec:
  accessModes:
    - {{ .Values.qdrant.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size }}
  storageClassName: {{ .Values.qdrant.persistence.storageClass }}
  volumeName: {{ .Release.Name }}-qdrant-gp2-pv
{{- end }}