apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-qdrant-efs-pv"
spec:
  capacity:
    storage: "{{ .Values.qdrant.persistence.size }}"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.qdrant.efs.fileSystemId }}" 