{{- if .Values.qdrant.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-qdrant-gp2-pv
spec:
  capacity:
    storage: {{ .Values.qdrant.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.qdrant.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.qdrant.persistence.storageClass }}
  hostPath:
    path: /tmp/qdrant-data
    type: DirectoryOrCreate
{{- end }} 