apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-efs-pv
spec:
  capacity:
    storage: 5Gi # Nominal value, EFS is elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc # Assumes efs-sc StorageClass exists cluster-wide
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.aktusEmbedding.efs.fileSystemId }}
    {{- if .Values.aktusEmbedding.efs.basePath }}
    volumeAttributes:
      path: {{ .Values.aktusEmbedding.efs.basePath | quote }}
    {{- end }} 