apiVersion: v2
dependencies:
- name: aktus-postgres-service
  repository: file://./charts/aktus-postgres-service
  tags:
  - infrastructure
  version: 1.0.0
- name: rabbitmq
  repository: file://./charts/rabbitmq
  tags:
  - infrastructure
  version: 1.0.0
- name: redis
  repository: file://./charts/redis
  tags:
  - infrastructure
  version: 1.0.0
- name: qdrant
  repository: file://./charts/qdrant
  tags:
  - infrastructure
  version: 1.0.0
- condition: aktus-database-service.enabled
  name: aktus-database-service
  repository: file://./charts/aktus-database-service
  version: 1.0.0
- condition: aktus-inference-service.enabled
  name: aktus-inference-service
  repository: file://./charts/aktus-inference-service
  version: 1.0.0
- condition: aktus-research-service.enabled
  name: aktus-research-service
  repository: file://./charts/aktus-research-service
  version: 1.0.0
- condition: aktus-multimodal-data-ingestion-service.enabled
  name: aktus-multimodal-data-ingestion-service
  repository: file://./charts/aktus-multimodal-data-ingestion-service
  version: 1.0.0
- condition: aktus-embedding-service.enabled
  name: aktus-embedding-service
  repository: file://./charts/aktus-embedding-service
  version: 1.0.0
- condition: aktus-knowledge-assistant.enabled
  name: aktus-knowledge-assistant-service
  repository: file://./charts/aktus-knowledge-assistant-service
  version: 1.0.0
description: Umbrella chart for Aktus AI platform
name: aktus-platform
type: application
version: 1.0.0
